### ISSUE TITLE
Error when using image references

### ISSUE THREAD

**Issue by pgengler** [showdownjs/showdown#585]
When using a markdown image that specifies the image URL via a footnote/reference, such as:

```
[![the-image]]

[the-image]: http://example.com/foo.png
```

the converter throws an error:
```
Uncaught TypeError: title.replace is not a function
    at writeImageTag (showdown.js:3702)
    at String.replace (<anonymous>)
    at showdown.js:3736
    at showdown.js:4191
    at showdown.js:4109
    at showdown.js:2844
    at showdown.Converter.makeHtml (showdown.js:2464)
```

Reproducible in [this JSFiddle](https://jsfiddle.net/r7ucf1xp/1/) using 1.8.6; I was also reproduce it locally with the `master` branch (2.0.0-alpha.1).

([GFM reference for this usage](https://github.github.com/gfm/#example-559))

**Comment by tivie** [comment]
Should be fixed now.

@pgengler can you please test if it's working for you?

---

> ### Donate [![Click here to lend your support to: ShowdownJS website and testing platform and make a donation at paypal.com](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.me/tiviesantos)
>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money.
>If you like our work and find our library useful, please donate ~~[through Pledgie](https://pledgie.com/campaigns/35166) or~~ directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated and help us continue to develop this awesome library.

**Comment by yuanjilee** [comment]
new version the issue is still exist

![image](https://user-images.githubusercontent.com/9959986/50280898-bf1e2d00-0488-11e9-9e14-db9f46706d1d.png)

**Comment by tivie** [comment]
Which version?

**Comment by yuanjilee** [comment]
@tivie 
> Which version?

with the http://demo.showdownjs.com/  test, is it the newest version?

test data:  `![[image] image](https://pbs.twimg.com/profile_images/704817777404743681/RNNOWR3X.jpg)`

**Comment by tivie** [comment]
@yuanjilee The issue you report is not related to this one. It has to do with "parentheses priority". 

You should open a new issue
