### ISSUE TITLE
Blockquote doesn't render

### ISSUE THREAD

**Issue by paviad** [showdownjs/showdown#938]
Blockquotes are not rendered, the `>` sign is visible and no solid grey line appears.

It is also broken in the demo:

http://demo.showdownjs.com/#!#blockquotes:~:text=for%20more%20info-,Blockquotes,-You%20can%20indicate

![image](https://user-images.githubusercontent.com/1235688/179456679-ea5de2ae-9480-4ae5-8bc6-bdff63f7792b.png)

**Comment by MarketingPip** [comment]
It appears this has been addressed. @paviad - here is an example of it working properly! 

[Blockquotes Working Demo](http://demo.showdownjs.com/#!/%3E%20block%20quotes%20are%20working!)

It appears you can close this issue!

**Comment by paviad** [comment]
It's still not published to NPM though, the script version in the demo is the tip of the main branch. Should I close this issue regardless? I feel it is not really resolved for me.

**Comment by paviad** [comment]
I am too silly.... I am showing the raw markdown in the picture... It actually worked in the demo all along. Sorry for the trouble.

**Comment by MarketingPip** [comment]
@paviad - I am not a maintainer of this project! 

Just throwing my two cents in to try and speed up / close some issues. 

Tho valid point - it does appear the version is not updated / matching the same as the demo. 

> I personally would leave this open till they see this.

**Comment by paviad** [comment]
It works perfectly, and has worked for a long time... I misinterpreted what I was seeing in the demo. And also in my own code I had a bug :)

**Comment by MarketingPip** [comment]
Correct me if I am wrong. I can not seem to get this working 

`> hello`

should become 

```
<blockquote>
  <p>hello</p>
</blockquote>
```


correct? 

Or is there a option that needs to be turned on for this? Would like an update / some help with this on my end - just looking at it now trying to help you! haha! (doesn't work in my version of showdown but works in demo) 

And if the case is we both need more :coffee: today - I would advise closing issue and if we are not losing our marbles. Leave it open! :+1: 

ps; not that we know each other etc but regardless - hope you're having a great weekend!

**Comment by paviad** [comment]
There is no option to be enabled, it works out of the box, and, yes, you are right, and I have closed this issue!

Thanks and you have a great weekend too! :)

**Comment by MarketingPip** [comment]
@paviad ah - I don't know how or why but I had an older version included that did not have the support needed for. 

Thanks for keeping me updated regardless tho & cheers :beers:

**Comment by MarketingPip** [comment]
@paviad assuming we both ran into the same issue and we were trying to take HTML to MD? 

That said, if that was the case. 

This means our block quotes were encoded with HTML entity.

Which I do believe - Showdown should provide a fix etc if the line starts with HTML entity for <code> > </code>  that it is replaced with a non HTML entity. 


So I would see this somewhat as a bug / feature request. 

🙏

**Comment by paviad** [comment]
Let me describe the bug that stopped me, the markdown text that I was trying to process using this library was in an html-encoded format so instead of the blockquote character `>` there was `&gt;` in the source text, that's why my markdown did not show it properly.

Once I decoded the input the markdown did process correctly, and blockquotes are rendered as `<blockquote>` tags. Then it's just css to style them (with a vertical line on the left for example).

**Comment by MarketingPip** [comment]
> Let me describe the bug that stopped me, the markdown text that I was trying to process using this library was in an html-encoded format so instead of the blockquote character `>` there was `&gt;` in the source text, that's why my markdown did not show it properly.
> 
> Once I decoded the input the markdown did process correctly, and blockquotes are rendered as `<blockquote>` tags. Then it's just css to style them (with a vertical line on the left for example).

Correct - so you faced the same problem as me. A <code>></code> being replaced with the HTML entity of <code> &gt;</code>

As <code>  &gt; and &lt; is a character entity reference for the > and < character in HTML</code>

I understand 100% that decoding should not happen in the script. And the user / developer should do this themselves. Tho this is a problem / bug. As if it starts on a new line with no characters behind it. It should be rendered as a block quote. Without you having to replace all matches of <code>&gt;</code> to <code>></code> as that acts more of a risk...
 
Hence why I say this is a bug now?

**Comment by paviad** [comment]
Not sure I understand why you think it is a bug in this library. The source markdown includes `>` for some reason (which is dependent on your particular implementation) it is encoded to `&gt;` you either have to stop that from happening, or decode it back before sending it to this library for processing.

**Comment by MarketingPip** [comment]
Again because block quote's require a >

Showdown automatically converts it into a > if you check.. (when using innerHTML content) and not text... 

Hence instead of causing risks by allowing > to not become a HTML entity (as it should).... 

A fix could be provided by checking if the > is on a new line and not followed before < which could be a script etc 
and kept as a >

To ensure block quote's get rendered. As well not posing a risk to a user / developer by replacing all `&gt;` to non HTML entities....

**Comment by paviad** [comment]
Doesn't showdown convert markdown to HTML and not the other way around?

You should be converting `>` into `<blockquote>` and not vice versa. So the `>` should be in your input.

I think your use case is different than mine. That is why I do not understand your meaning all the way.

**Comment by paviad** [comment]
I don't feel comfortable leaving this issue open when it is not really the issue I was facing, and also I don't fully understand your use case.

I'd rather you open a new issue and describe your use case in more detail.
